version: '3.8'

services:
  # 1. Database MongoDB
  traffic_mongodb:
    image: mongo:5.0
    container_name: traffic_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  # 2. Web quản lý (Mongo Express)
  mongo-express:
    image: mongo-express
    container_name: traffic_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # Kết nối thẳng vào container bên trên bằng tên service
      ME_CONFIG_MONGODB_URL: mongodb://root:password@traffic_mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    links:
      - traffic_mongodb

volumes:
  mongo_data: